import 'package:get/get.dart';

class AppTranslations extends Translations {
  //used for translation in the app
  @override
  Map<String, Map<String, String>> keys = {
    'en': {
      'Products': 'Products',
      'Notihing to show\nAdd Items to Cart':
          'Nothing to show\nAdd Items to Cart',
      'Shop Now': 'Shop Now',
      'Your Cart Total': 'Your Cart Total',
      'Cart Items': 'Cart Items',
      'Successfully Purchased Order': 'Successfully Purchased Order',
      'Buy': 'Buy',
      'Order History': 'Order History',
      'Order No': 'Order No',
      'Ordered': 'Ordered',
      'Order Total': 'Order Total',
      'View Info': 'View Info',
      'Order Details': 'Order Details',
      'at price': 'at price',
      'each': 'each',
      'Price: Low to High': 'Price: Low to High',
      'Price: High to Low': 'Price: High to Low',
      'Name': 'Name',
      'All': 'All',
      'Electronics': 'Electronics',
      'Jewelery': 'Jewelery',
      'Men\'s Clothing': 'Men\'s Clothing',
      'Women\'s Clothing': 'Women\'s Clothing',
      'Filter By Category': 'Filter By Category',
      'Sort By': 'Sort By',
      'Add to Cart': 'Add to Cart',
    },
    'hi': {
      'Products': 'उत्पाद',
      'Notihing to show\nAdd Items to Cart':
          'कुछ नहीं दिखा\nकार्ट में आइटम जोड़ें',
      'Shop Now': 'अब खरीदें',
      'Your Cart Total': 'आपकी कार्ट कुल',
      'Cart Items': 'कार्ट आइटम्स',
      'Successfully Purchased Order': 'सफलतापूर्वक खरीदी गई ऑर्डर',
      'Buy': 'खरीदें',
      'Order History': 'ऑर्डर इतिहास',
      'Order No': 'ऑर्डर नंबर',
      'Ordered': 'ऑर्डर किया गया',
      'Order Total': 'ऑर्डर कुल',
      'View Info': 'जानकारी देखें',
      'Order Details': 'ऑर्डर विवरण',
      'at price': 'की कीमत पर',
      'each': 'प्रत्येक',
      'Price: Low to High': 'मूल्य: निम्न से उच्च',
      'Price: High to Low': 'मूल्य: उच्च से निम्न',
      'Name': 'नाम',
      'All': 'सभी',
      'Electronics': 'इलेक्ट्रॉनिक्स',
      'Jewelery': 'गहने',
      'Men\'s Clothing': 'पुरुषों के वस्त्र',
      'Women\'s Clothing': 'महिलाओं के वस्त्र',
      'Filter By Category': 'श्रेणी द्वारा फ़िल्टर करें',
      'Sort By': 'क्रमबद्ध करें',
      'Add to Cart': 'कार्ट में डालें',
    },
    'mr': {
      'Products': 'उत्पाद',
      'Notihing to show\nAdd Items to Cart':
          'दाखविण्यासाठी काही नाही\nकार्टमध्ये आयटम जोडा',
      'Shop Now': 'आता खरेदी करा',
      'Your Cart Total': 'तुमची कार्ट एकूण',
      'Cart Items': 'कार्ट आयटम्स',
      'Successfully Purchased Order': 'यशस्वी खरेदी केलेली ऑर्डर',
      'Buy': 'खरेदी करा',
      'Order History': 'ऑर्डर इतिहास',
      'Order No': 'ऑर्डर क्र.',
      'Ordered': 'ऑर्डर केलेले',
      'Order Total': 'ऑर्डर एकूण',
      'View Info': 'माहिती पहा',
      'Order Details': 'ऑर्डर तपशील',
      'at price': 'किंमतीवर',
      'each': 'प्रत्येक',
      'Price: Low to High': 'किंमत: कमी ते जास्त',
      'Price: High to Low': 'किंमत: जास्त ते कमी',
      'Name': 'नाव',
      'All': 'सर्व',
      'Electronics': 'इलेक्ट्रॉनिक्स',
      'Jewelery': 'दागिने',
      'Men\'s Clothing': 'पुरुषांचे वस्त्र',
      'Women\'s Clothing': 'महिलांचे वस्त्र',
      'Filter By Category': 'वर्गानुसार फिल्टर करा',
      'Sort By': 'क्रमवारी ठेवा',
      'Add to Cart': 'कार्टमध्ये जोडा',
    },
  };
}
